class AddKeys < ActiveRecord::Migration
  def change
    add_foreign_key "ads_images", "advertisments", name: "ads_images_advertisment_id_fk"
    add_foreign_key "advertisments", "types", name: "advertisments_type_id_fk"
    add_foreign_key "advertisments", "users", name: "advertisments_user_id_fk"
    add_foreign_key "cars", "advertisments", name: "cars_advertisment_id_fk"
    add_foreign_key "cars", "cities", name: "cars_city_id_fk"
    add_foreign_key "cars", "colors", name: "cars_color_id_fk"
    add_foreign_key "cars", "conditions", name: "cars_condition_id_fk"
    add_foreign_key "cars", "countries", name: "cars_country_id_fk"
    add_foreign_key "cars", "doors", name: "cars_door_id_fk"
    add_foreign_key "cars", "engines", name: "cars_engine_id_fk"
    add_foreign_key "cars", "engine_volumes", name: "cars_engine_volume_id_fk"
    add_foreign_key "cars_features", "cars", name: "cars_features_car_id_fk"
    add_foreign_key "cars_features", "features", name: "cars_features_feature_id_fk"
    add_foreign_key "cars", "makes", name: "cars_make_id_fk"
    add_foreign_key "cars", "mileages", name: "cars_mileage_id_fk"
    add_foreign_key "cars", "models", name: "cars_model_id_fk"
    add_foreign_key "cars", "styles", name: "cars_style_id_fk"
    add_foreign_key "cars", "transmissions", name: "cars_transmission_id_fk"
    add_foreign_key "cars", "years", name: "cars_year_id_fk"
    add_foreign_key "cities", "countries", name: "cities_country_id_fk"
    add_foreign_key "comments", "advertisments", name: "comments_advertisment_id_fk"
    add_foreign_key "comments", "users", name: "comments_user_id_fk"
    add_foreign_key "models", "makes", name: "models_make_id_fk"
    add_foreign_key "reviews", "users", name: "reviews_assignee_id_fk", column: "assignee_id"
    add_foreign_key "reviews", "users", name: "reviews_user_id_fk"
  end
end
