default: &default
  adapter: postgresql
  host: example
  username: example
  password: example
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ads_development

test:
  <<: *default
  database: ads_test

production:
  <<: *default
  database: ads_production